name: TF
channels:
  - ambermd
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.11.0=pyhd3eb1b0_1
  - astor=0.8.1=py37_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.17.1=h9ed2024_0
  - ca-certificates=2020.12.8=hecd8cb5_0
  - certifi=2020.12.5=py37hecd8cb5_0
  - curl=7.71.1=hb0a8c7a_1
  - cycler=0.10.0=py37_0
  - freetype=2.10.4=ha233b18_0
  - gast=0.2.2=py37_0
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py37h7580e61_0
  - h5py=2.10.0=py37h3134771_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2019.4=233
  - jpeg=9b=he5867d9_2
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.3.0=py37h23ab428_0
  - krb5=1.18.2=h75d18d8_0
  - lcms2=2.11=h92f6f08_0
  - libcurl=7.71.1=h8a08a2b_1
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libnetcdf=4.7.3=he3b6227_0
  - libpng=1.6.37=ha441bb4_0
  - libprotobuf=3.13.0.1=hab81aa3_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.1.0=hcb84e12_1
  - lz4-c=1.9.2=h79c402e_3
  - markdown=3.3.3=py37hecd8cb5_0
  - matplotlib=3.3.2=0
  - matplotlib-base=3.3.2=py37h181983e_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.2.0=py37hc64f4ea_0
  - mkl_random=1.1.1=py37h959d312_0
  - ncurses=6.2=h0a44026_1
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - olefile=0.46=py37_0
  - openssl=1.1.1i=h9ed2024_0
  - opt_einsum=3.1.0=py_0
  - pillow=8.0.1=py37h5270095_0
  - pip=20.3.1=py37hecd8cb5_0
  - protobuf=3.13.0.1=py37hb1e8313_1
  - pyparsing=2.4.7=py_0
  - python=3.7.9=h26836e1_0
  - python-dateutil=2.8.1=py_0
  - pytraj=2.0.5=py37_0
  - readline=8.0=h1de35cc_0
  - scipy=1.5.2=py37h912ce22_0
  - setuptools=51.0.0=py37hecd8cb5_2
  - six=1.15.0=py37hecd8cb5_0
  - sqlite=3.33.0=hffcf06c_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=mkl_py37hda344b4_0
  - tensorflow-base=2.0.0=mkl_py37h66b1bf0_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py37h9ed2024_0
  - werkzeug=1.0.1=py_0
  - wheel=0.36.1=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h1de35cc_1
  - xz=5.2.5=h1de35cc_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
prefix: /Users/dylanabramson/opt/anaconda3/envs/TF
